name: login

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-sign:
    environment: production

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: azure login
        uses: azure/login@v2
        with:
          allow-no-subscriptions: true
          client-id: ${{ secrets.KEYVAULT_CLIENT_ID }}
          tenant-id: ${{ secrets.KEYVAULT_TENANT_ID }}
