name: sign

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-sign:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: build
        run: dotnet build --configuration Release --no-restore

      - name: publish
        run: dotnet publish --configuration Release --no-build -o ./artifacts

      - name: artifact
        uses: actions/upload-artifact@v5
        with:
          name: AcmeLibrary
          path: artifacts
